apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-backend
  template:
    metadata:
      labels:
        app: my-node-backend
    spec:
      containers:
        - name: my-node-backend
          image: shouryap1/backend:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"    # Added CPU requests
            limits:
              memory: "512Mi"
              cpu: "500m"    # Added CPU limits
          env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: mongo-url
